name: PrivateGamesAddon
version: '${project.version}'
main: me.harsh.privategamesaddon.PrivateGamesPlugin
api-version: 1.13
depend:
  - MBedwars
commands:
  privategames:
    description: Create private matches
    usage: /bwp [args...]