# ============================================
#
#     P R I V A T E  G A M E S  A D D O N
#
# ============================================
Features:
  # If Set to true it will register the stats of the private games to player
  Save_Stats: false
  # If set to true the perms set in the Perms section of that buff will be used
  Per_buff_perm: false
Placeholders:
  # This placeholder can be used inside Scoreboard to present if the game is private or not! [P] on hypixel
  Is_private_game: '[P]' # Color Codes not supported
Perms:
  # Dont add spaces here!
  admin_perm: 'privategame.admin' # Gives all the perms except reload and create
  create_perm: 'privategame.create'
  reload_perm: 'privategame.reload'
  # Per buff permissions
  Buffs:
Menu:
  Title: '&cPrivate &aGames Menu'
  Control_panel: "&c&lADMIN PANEL"

  Sub_Menu:
    Speed: 'Speed Buff Menu'
    Respawn: 'Respawn Buff Menu'
    Health: 'Custom Health Buff'
    Spawn_rate: 'Spawn rate Buff'


# -------------------------------------------
#         COMMAND ALIASES (/bwp is always included by default)
# -------------------------------------------

Command_Aliases: ["bwp"]


# -----------------------------
#       DO NOT CHANGE
# -----------------------------

Debug: []
Version: 1