# Private Games Addon
Prefix: '&cPrivate Games Addon&7>>'
# If Set to true it will register the stats of the private games to player
Save_Stats: false
Placeholders:
  is_private_game: '&7[Private]'
Perms:
  global_perm: 'privategame.*'
  create_perm: 'privategame.create'
Menu:
  Title: '&cPrivate &aGames Control Menu'
  Sub_Menu:
    Speed: 'Speed Buff Menu'
    Respawn: 'Respawn Buff Menu'
    Health: 'Custom Health Buff'
  Buffs:
    One_Hit_Buff: '&aOne Hit Buff'
    Health_Buff: '&aHealth Buff'
    Low_Gravity_Buff: '&aLow Gravity'
    Speed_Buff: '&aSpeed Buff'
    Disable_Block_Protection_Buff: '&aDisable Block Protection'
    Respawn_Time_Buff: '&aRespawn Time Buff'
    Spawn_Rate_Mutiplier_Buff: '&aSpawn Rate Multiplier'














Log_Lag_Over_Milis: 100
Version: 1
Debug: []