# ============================================
#
#     P R I V A T E  G A M E S  A D D O N
#
# ============================================
Features:
  # If Set to true it will register the stats of the private games to player
  Save_Stats: false
  # If set to false you will have to manually use /bwp warp when you create a private game
  Auto_warp: true
  # Which plugin to use as party plugin if found all three supported plugins
  # [ Paf , Parties , BP , PafB]
  Priority: BP
  # If set to true the perms set in the Perms section of that buff will be used..
  Per_buff_perm: false
Placeholders:
  # This placeholder can be used inside Scoreboard to present if the game is private or not! [P] on hypixel
  Is_private_game: '[P]' # Color Codes not supported
Perms:
  # Dont add spaces here!
  admin_perm: 'privategame.admin' # Gives all the perms except reload and create
  create_perm: 'privategame.create'
  reload_perm: 'privategame.reload'
  auto_warp: 'privategame.autowarp'
  # Per buff permissions
  Buffs:
    One_hit_buff_perm: "privategame.buffs.onehit"
    Custom_health_buff_perm: "privategame.buffs.health"
    Gravity_buff_perm: "privategame.buffs.gravity"
    Respawn_time_buff_perm: "privategame.buffs.respawn"
    No_special_spawner_buff_perm: "privategame.buffs.nospawner"
    Speed_buff_perm: "privategame.buffs.speed"
    No_fall_damage_buff_perm: "privategame.buffs.falldamage"
    Max_upgrades_buff_perm: "privategame.buffs.maxupgrade"
    Block_protection_buff_perm: "privategame.buffs.blockprot"
    Spawn_rate_multiplier: "privategame.buffs.spawnrate"
Menu:
  Title: '&cPrivate &aGames Menu'
  Control_panel: "&c&lADMIN PANEL"

  Sub_Menu:
    Speed: 'Speed Buff Menu'
    Respawn: 'Respawn Buff Menu'
    Health: 'Custom Health Buff'
    Spawn_rate: 'Spawn rate Buff'


# -------------------------------------------
#         COMMAND ALIASES (/bwp is always included by default)
# -------------------------------------------

Command_Aliases: ["bwp"]


# -----------------------------
#       DO NOT CHANGE
# -----------------------------

Debug: []
Version: 1